name: Build and Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  # Trigger the workflow on pull request (only for the master branch)
  # push:
  #   branches:
  #     - '**'
  #   paths-ignore:
  #     - '**/media/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/media/**'

jobs:  
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]
    defaults:
      run:
        shell: bash

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm test
